spring.application.name=clean-spring-boot

# SQL Server Datasource Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=myDb;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Pwd#196482627
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA Configuration (if using JPA/Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
