@startuml
'https://plantuml.com/sequence-diagram

title EvaluatePromotionRuleDetail POST /api/v1/promotion-rules/evaluate?mode=light

actor Client
participant "PromotionRedeemController\n(infrastructure/adapter/in/web)" as Controller
participant "PromotionEvaluationService\n(application/service)" as Service
participant "PromotionEvaluationService\n(domain/service)" as DomainService
participant "PromotionRuleRepository\n(infrastructure/adapter/out/persistence)" as Repository

Client -> Controller
activate Controller
'Controller -> Controller: validateQueryParams
'alt invalid parameters
'    Client <-- Controller: 400
'    note right of Client
'    {
'      "code": "invalid_request",
'      "message": "Invalid status value"
'    }
'    end note
'    deactivate Controller
'end



'RuleIndex -> RuleIndex: lookup SKU ruleIds\n( product_rule_map[sku] )
'RuleIndex -> RuleIndex: lookup category ruleIds\n( category_rule_map[category] )
'RuleIndex -> RuleIndex: lookup payment ruleIds\n( payment_rule_map[payment] )
'RuleIndex -> RuleIndex: lookup segment ruleIds\n( segment_rule_map[segment] )


Controller -> Service: evaluatePromotionRules(item, mode)
activate Service

Service -> DomainService: evaluatePromotionRules(item, mode)
activate DomainService

DomainService -> Repository: find
activate Repository

Repository -> Repository: query database
note right of Repository
ref: ~/resources/db.migrations/V1_create_promotion_rules_tables.sql
-- promotion_rules
end note

Repository --> Service: PromotionRuleEntity
deactivate Repository

Service -> Service: transformToPromotionRuleDTO(promotionRuleEntity)
Service --> Controller: PromotionRuleResponse
deactivate Service

Controller --> Client: 200 OK
note right of Client
return ref: tags: [promotionRule]  ~/openapi/promotion-engine-api.yaml
end note
deactivate Controller

@enduml

