@startuml
'https://plantuml.com/sequence-diagram

title EvaluatePromotionRuleDetail POST /api/v1/promotion-rules/evaluate

actor Client
participant "PromotionRedeemController\n(infrastructure/adapter/in/web)" as Controller
participant "PromotionEvaluationService\n(application/service)" as Service
participant "PromotionRuleRepository\n(infrastructure/adapter/out/persistence)" as Repository

Client -> Controller
activate Controller
'Controller -> Controller: validateQueryParams
'alt invalid parameters
'    Client <-- Controller: 400
'    note right of Client
'    {
'      "code": "invalid_request",
'      "message": "Invalid status value"
'    }
'    end note
'    deactivate Controller
'end

Controller -> Service: getPromotionRuleDetail(ruleId)
activate Service

Service -> Repository: findById(ruleId)
activate Repository

Repository -> Repository: query database
note right of Repository
ref: ~/resources/db.migrations/V1_create_promotion_rules_tables.sql
-- promotion_rules
end note

Repository --> Service: PromotionRuleEntity
deactivate Repository

Service -> Service: transformToPromotionRuleDTO(promotionRuleEntity)
Service --> Controller: PromotionRuleResponse
deactivate Service

Controller --> Client: 200 OK
note right of Client
return ref: tags: [promotionRule]  ~/openapi/promotion-engine-api.yaml
end note
deactivate Controller

@enduml

